CREATE TABLE IF NOT EXISTS user_accounts (
    id SERIAL PRIMARY KEY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    balance DOUBLE NOT NULL DEFAULT 0,
    status VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_on TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS transactions (
     id SERIAL PRIMARY KEY PRIMARY KEY,
    user_account_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    amount DOUBLE NOT NULL DEFAULT 0,
    currency VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_on TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);